// Auth action types
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST"
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS"
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE"

export const LOGOUT = "LOGOUT"

// Personal Details action types
export const SAVE_PERSONAL_DETAILS_REQUEST = "SAVE_PERSONAL_DETAILS_REQUEST"
export const SAVE_PERSONAL_DETAILS_SUCCESS = "SAVE_PERSONAL_DETAILS_SUCCESS"
export const SAVE_PERSONAL_DETAILS_FAILURE = "SAVE_PERSONAL_DETAILS_FAILURE"

// Investment Preferences action types
export const SAVE_INVESTMENT_PREFERENCES_REQUEST = "SAVE_INVESTMENT_PREFERENCES_REQUEST"
export const SAVE_INVESTMENT_PREFERENCES_SUCCESS = "SAVE_INVESTMENT_PREFERENCES_SUCCESS"
export const SAVE_INVESTMENT_PREFERENCES_FAILURE = "SAVE_INVESTMENT_PREFERENCES_FAILURE"

// KYC action types
export const SUBMIT_KYC_REQUEST = "SUBMIT_KYC_REQUEST"
export const SUBMIT_KYC_SUCCESS = "SUBMIT_KYC_SUCCESS"
export const SUBMIT_KYC_FAILURE = "SUBMIT_KYC_FAILURE"

// Contact action types
export const SUBMIT_CONTACT_REQUEST = "SUBMIT_CONTACT_REQUEST"
export const SUBMIT_CONTACT_SUCCESS = "SUBMIT_CONTACT_SUCCESS"
export const SUBMIT_CONTACT_FAILURE = "SUBMIT_CONTACT_FAILURE"

// UI action types
export const SET_LOADING = "SET_LOADING"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
